#!/usr/bin/env bash

set -e

outdir="library"
docker_platforms=( "386" "amd64" "armv6" "armv7" "arm64" "riscv64" "s390x" )

GITHUB_REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER:-"socheatsok78"}
GITHUB_REPOSITORY=${GITHUB_REPOSITORY:-"${GITHUB_REPOSITORY_OWNER}/docker-s6-overlay"}
S6_GITHUB_REPOSITORY=just-containers/s6-overlay

function releases() {
	gh api repos/${S6_GITHUB_REPOSITORY}/releases --jq '.[].tag_name'
}

function releases_filter() {
	grep "v3.2"
}

function s6_archive() {
	case "${1}" in
		"386") echo "i686";;
		"amd64") echo "x86_64";;
		"arm64") echo "aarch64";;
		"armv6") echo "armhf";;
		"armv7") echo "arm";;
		"riscv64") echo "riscv64";;
		"s390x") echo "s390x";;
	esac
}

function build_platform() {
	case "${1}" in
		"386") echo "linux/386";;
		"amd64") echo "linux/amd64";;
		"armv6") echo "linux/arm/v6";;
		"armv7") echo "linux/arm/v7";;
		"arm64") echo "linux/arm64";;
		"riscv64") echo "linux/riscv64";;
		"s390x") echo "linux/s390x";;
	esac
}

function dockerbakefile() {
	local version="$1"
	echo "// This file is generated by \"$(basename "$0")\" script, do not edit it manually."
	echo "variable \"GITHUB_REPOSITORY_OWNER\" {"
	echo "  default = \"socheatsok78\""
	echo "}"
	echo ""
	echo "variable \"GITHUB_REPOSITORY\" {"
	echo "  default = \"\${GITHUB_REPOSITORY_OWNER}/docker-s6-overlay\""
	echo "}"
	echo ""
	echo "target \"docker-metadata-action\" {}"
	echo "target \"github-metadata-action\" {}"
	echo ""
	echo "group \"default\" {"
	echo "  targets = ["
	echo "    \"s6-overlay\","
	echo "    \"s6-overlay-symlinks\","
	echo "    \"s6-overlay-syslogd\","
	echo "  ]"
	echo "}"
	echo ""
	echo "target \"s6-overlay\" {"
	echo "  inherits = [ \"docker-metadata-action\", \"github-metadata-action\" ]"
	echo "  target = \"s6-overlay\""
	echo "  platforms = ["
	for arch in "${docker_platforms[@]}"; do
		echo "    \"$(build_platform "$arch")\","
	done
	echo "  ]"
	echo "  tags = ["
	echo "    \"docker.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:${version}\","
	echo "    \"ghcr.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:${version}\","
	echo "  ]"
	echo "}"
	echo ""
	echo "target \"s6-overlay-symlinks\" {"
	echo "  inherits = [ \"docker-metadata-action\", \"github-metadata-action\" ]"
	echo "  target = \"s6-overlay-symlinks\""
	echo "  platforms = ["
	for arch in "${docker_platforms[@]}"; do
		echo "    \"$(build_platform "$arch")\","
	done
	echo "  ]"
	echo "  tags = ["
	echo "    \"docker.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:${version}-symlinks\","
	echo "    \"ghcr.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:${version}-symlinks\","
	echo "  ]"
	echo "}"
	echo ""
	echo "target \"s6-overlay-syslogd\" {"
	echo "  inherits = [ \"docker-metadata-action\", \"github-metadata-action\" ]"
	echo "  target = \"s6-overlay-syslogd\""
	echo "  platforms = ["
	for arch in "${docker_platforms[@]}"; do
		echo "    \"$(build_platform "$arch")\","
	done
	echo "  ]"
	echo "  tags = ["
	echo "    \"docker.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:${version}-syslogd\","
	echo "    \"ghcr.io/\${replace(GITHUB_REPOSITORY, \"docker-\", \"\")}:${version}-syslogd\","
	echo "  ]"
	echo "}"
}

function dockerfile() {
	local version="$1"
	echo "# syntax=docker/dockerfile:1"
	echo "# This file is generated by \"$(basename "$0")\" script, do not edit it manually."
	echo ""
	echo "FROM scratch AS s6-overlay-noarch"
	echo "ADD --unpack=true --checksum=sha256:$(curl --fail -s -L "https://github.com/${S6_GITHUB_REPOSITORY}/releases/download/${version}/s6-overlay-noarch.tar.xz.sha256" | cut -d" " -f1) https://github.com/${S6_GITHUB_REPOSITORY}/releases/download/${version}/s6-overlay-noarch.tar.xz /"
	echo ""
	for arch in "${docker_platforms[@]}"; do
		echo "FROM s6-overlay-noarch AS s6-overlay-$arch"
		echo "ADD --unpack=true --checksum=sha256:$(curl --fail -s -L "https://github.com/${S6_GITHUB_REPOSITORY}/releases/download/${version}/s6-overlay-$(s6_archive "$arch").tar.xz.sha256" | cut -d" " -f1) https://github.com/${S6_GITHUB_REPOSITORY}/releases/download/${version}/s6-overlay-$(s6_archive "$arch").tar.xz /"
		echo ""
	done
	echo "# s6-overlay"
	echo "# This is the default target for s6-overlay, the architecture and variant will be determined by the build platform"
	echo "FROM s6-overlay-\${TARGETARCH}\${TARGETVARIANT} AS s6-overlay"
	echo "FROM s6-overlay"
	echo ""
	echo "# s6-overlay-symlinks-noarch.tar.xz & s6-overlay-symlinks-arch.tar.xz"
	echo "FROM scratch AS s6-overlay-symlinks"
	for arch in "noarch" "arch"; do
		echo "ADD --unpack=true --checksum=sha256:$(curl --fail -s -L "https://github.com/${S6_GITHUB_REPOSITORY}/releases/download/${version}/s6-overlay-symlinks-${arch}.tar.xz.sha256" | cut -d" " -f1) https://github.com/${S6_GITHUB_REPOSITORY}/releases/download/${version}/s6-overlay-symlinks-${arch}.tar.xz /"
	done
	echo ""
	echo "# syslogd-overlay-noarch.tar.xz"
	echo "FROM scratch AS s6-overlay-syslogd"
	echo "ADD --unpack=true --checksum=sha256:$(curl --fail -s -L "https://github.com/${S6_GITHUB_REPOSITORY}/releases/download/${version}/syslogd-overlay-noarch.tar.xz.sha256" | cut -d" " -f1) https://github.com/${S6_GITHUB_REPOSITORY}/releases/download/${version}/syslogd-overlay-noarch.tar.xz /"
	echo ""
}

function main() {
	while [ "$#" -gt 0 ]; do
		case "$1" in
			--outdir)
				outdir="$2"
				shift 2
				;;
			--overwrite)
				overwrite=true
				echo "INF: Overwrite mode enabled, existing versions will be overwritten."
				shift 1
				;;
			*)
				echo "Usage: $0 [--overwrite] [--outdir <output directory>]"
				exit 1
				;;
		esac
	done
	releases | releases_filter | while read -r version; do
		if [ "${overwrite}" = true ]; then
			rm -rf "${outdir:?}/${version}"
		fi
		if [ -d "${outdir:?}/${version}" ]; then
			echo "WRN: Skipping version ${version} because it already exists."
			continue
		fi
		echo "INF: Generating files for release ${version}..."
		mkdir -p "${outdir:?}/${version}"
		dockerbakefile "$version" > "${outdir:?}/${version}/docker-bake.hcl"
		dockerfile "$version" > "${outdir:?}/${version}/Dockerfile"
	done
}

main "${@}"
