name: "Build"

on:
  workflow_dispatch:
    inputs:
      permit-push:
        type: boolean
        description: 'Permit push to registry'
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1
      - name: Generate matrix
        id: generate
        run: ./.github/scripts/generate-build-matrix.sh

  s6-overlay:
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.matrix) }}
    permissions:
      contents: read
      packages: write
    uses: socheatsok78/uses/.github/workflows/docker-buildx-bake.yml@main
    with:
      flavor: latest=false
      tags: type=raw,value=${{ matrix.version }}
      permit-login: ${{ inputs.permit-push || github.event_name != 'pull_request' }}
      permit-push: ${{ inputs.permit-push || github.event_name != 'pull_request' }}
      permit-cache: true
    secrets: inherit
