name: "Build"

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - id: releases
        uses: actions-matrix/github-release-matrix-action@v1
        with:
          repository: "just-containers/s6-overlay"
        env:
          GH_TOKEN: ${{ github.token }}
    outputs:
      matrix: ${{ steps.releases.outputs.matrix }}

  base:
    needs: generate
    strategy:
      matrix: ${{ fromJson(needs.generate.outputs.matrix) }}
    uses: ./.github/workflows/docker-build-release.yml
    with:
      targets: s6-overlay
      push: ${{ github.event_name != 'pull_request' }}
      images: |
        docker.io/${{ github.actor }}/s6-overlay
        ghcr.io/${{ github.actor }}/s6-overlay
      tag_name: ${{ matrix.releases.tag_name }}
    secrets: inherit

  symlinks:
    needs: generate
    strategy:
      matrix: ${{ fromJson(needs.generate.outputs.matrix) }}
    uses: ./.github/workflows/docker-build-release.yml
    with:
      targets: s6-overlay-symlinks
      push: ${{ github.event_name != 'pull_request' }}
      images: |
        docker.io/${{ github.actor }}/s6-overlay
        ghcr.io/${{ github.actor }}/s6-overlay
      tag_name: ${{ matrix.releases.tag_name }}
      tag_suffix: symlinks
    secrets: inherit

  syslogd:
    needs: generate
    strategy:
      matrix: ${{ fromJson(needs.generate.outputs.matrix) }}
    uses: ./.github/workflows/docker-build-release.yml
    with:
      targets: s6-overlay-syslogd
      push: ${{ github.event_name != 'pull_request' }}
      images: |
        docker.io/${{ github.actor }}/s6-overlay
        ghcr.io/${{ github.actor }}/s6-overlay
      tag_name: ${{ matrix.releases.tag_name }}
      tag_suffix: syslogd
    secrets: inherit
