on:
  workflow_call:
    inputs:
      targets:
        description: 'The targets to build.'
        required: true
        type: string
      push:
        description: 'Whether to push the built images.'
        required: false
        type: boolean
        default: false
      images:
        description: 'The Docker images to build.'
        required: true
        type: string
      tag_name:
        description: 'The tag name to use for the release.'
        required: true
        type: string
      tag_suffix:
        description: |
          The `tag_name` suffix to use for the release.
          
          If not provided, no suffix will be added.
          Otherwise, it will be appended to the `tag_name` with a hyphen.

          E.g. `symlinks` will result in `tag_name-symlinks`.
        required: false
        type: string
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker metadata
        id: docker-meta
        uses: docker/metadata-action@v5
        env:
          S6_VERSION: ${{ inputs.tag_name }}
        with:
          images: ${{ inputs.images}}
          flavor: latest=false
          tags: type=raw,value=${{ inputs.tag_name }}${{ (inputs.tag_suffix != '' && format('-{0}', inputs.tag_suffix)) || '' }}

      - name: Generate GitHub metadata
        id: github-meta
        uses: dockerbakery/github-metadata-action@v2

      - name: Build and push
        uses: docker/bake-action@v6
        with:
          targets: ${{ inputs.targets }}
          push: ${{ inputs.push }}
          source: .
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.docker-meta.outputs.bake-file }}
            cwd://${{ steps.github-meta.outputs.bake-file }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
