name: "Manual build"

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 's6-overlay tag name'
        required: true
      push:
        description: 'Enable pushing to Registries'
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  base:
    uses: ./.github/workflows/docker-build-release.yml
    with:
      targets: s6-overlay
      push: ${{ github.event_name != 'pull_request' }}
      images: |
        docker.io/${{ github.actor }}/s6-overlay
        ghcr.io/${{ github.actor }}/s6-overlay
      tag_name: ${{ inputs.tag_name }}
    secrets: inherit

  symlinks:
    uses: ./.github/workflows/docker-build-release.yml
    with:
      targets: s6-overlay-symlinks
      push: ${{ github.event_name != 'pull_request' }}
      images: |
        docker.io/${{ github.actor }}/s6-overlay
        ghcr.io/${{ github.actor }}/s6-overlay
      tag_name: ${{ inputs.tag_name }}
      tag_suffix: symlinks
    secrets: inherit

  syslogd:
    uses: ./.github/workflows/docker-build-release.yml
    with:
      targets: s6-overlay-syslogd
      push: ${{ github.event_name != 'pull_request' }}
      images: |
        docker.io/${{ github.actor }}/s6-overlay
        ghcr.io/${{ github.actor }}/s6-overlay
      tag_name: ${{ inputs.tag_name }}
      tag_suffix: syslogd
    secrets: inherit
