name: "Test"

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - next
      - trunk
    paths:
      - "Dockerfile"
      - "docker-bake.hcl"
  pull_request:
    branches:
      - develop
      - next
      - trunk
    paths:
      - "Dockerfile"
      - "docker-bake.hcl"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - id: releases
        uses: actions-matrix/github-release-matrix-action@v1
        with:
          repository: "just-containers/s6-overlay"
        env:
          GH_TOKEN: ${{ github.token }}
    outputs:
      matrix: ${{ steps.releases.outputs.matrix }}

  base:
    needs: generate
    strategy:
      matrix: ${{ fromJson(needs.generate.outputs.matrix) }}
    uses: ./.github/workflows/use-docker-build-test.yml
    with:
      targets: s6-overlay
      push: false
      images: |
        docker.io/${{ github.repository_owner }}/s6-overlay
        ghcr.io/${{ github.repository_owner }}/s6-overlay
      tag_name: ${{ matrix.releases.tag_name }}

  symlinks:
    needs: generate
    strategy:
      matrix: ${{ fromJson(needs.generate.outputs.matrix) }}
    uses: ./.github/workflows/use-docker-build-test.yml
    with:
      targets: s6-overlay-symlinks
      push: false
      images: |
        docker.io/${{ github.repository_owner }}/s6-overlay
        ghcr.io/${{ github.repository_owner }}/s6-overlay
      tag_name: ${{ matrix.releases.tag_name }}
      tag_suffix: symlinks

  syslogd:
    needs: generate
    strategy:
      matrix: ${{ fromJson(needs.generate.outputs.matrix) }}
    uses: ./.github/workflows/use-docker-build-test.yml
    with:
      targets: s6-overlay-syslogd
      push: false
      images: |
        docker.io/${{ github.repository_owner }}/s6-overlay
        ghcr.io/${{ github.repository_owner }}/s6-overlay
      tag_name: ${{ matrix.releases.tag_name }}
      tag_suffix: syslogd
